title: GPT-3 Playground
description: >-
  Note that this plugin costs approximate one cent for every three documents analyzed, depending on the length and complexity of the prompt and documents. Give this a full prompt that you would pass into GPT-3 and it will run it against your selected documents, one at a time. Only looks at the first page of a document currently.
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the currently selected documents
  - selected
# Properties can just be blank if you do not need any input data
properties:
  # the key is the name of the variable that will be returned to your code
  prompt:
    # the title is what will be shown as the form label
    title: Give a GPT-3 style prompt
    # a string is text
    type: string
