title: GPT-3 Playground (Alpha)
description: |
  Use GPT3 to help analyze your documents, right within DocumentCloud. Note
  that this Add-On consumes AI credits, which you can get via a Pro or Organization
  account.

  Give this a full prompt that you would pass into GPT-3 and it will run it
  against your selected documents, one at a time. The Add-On currently looks at 
  the first 12,000 characters in each document, which is about six pages of text on average.
  
  We'd love your feedback and ideas — drop a note to info at documentcloud dot org or join
  us in the News Nerdery Slack in the #proj-documentcloud channel.
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  prompt:
    title: Give a GPT-3 style prompt
    type: string
  value:
    title: Put a tag here if you would like to save the results as a key value pair on the document.
    type: string

required:
  - prompt
categories:
  - ai
  - premium
cost:
  price: 14
  amount: 1
  unit: document
