title: GPT-3 Playground (Alpha)
description: |
  Use GPT3 to help analyze your documents, right within DocumentCloud.

  Give this a full prompt that you would pass into GPT-3 and it will run it
  against your selected documents, one at a time. 
  
  The Add-On currently looks at the first 56,000 characters in each document, 
  which is about the first 35 pages of text if using an average page size of 300 words per page. 

  The Add-On cost is approximately 1 AI credit per page, if your document hovers around 300 words per page.
  If your document has much more text per page, it may be more costly. 
  
  There is a dry-run option that tells you the cost of running the Add-On on your entire set without charging you. 
  The cost is capped at 35 AI credits per document per run. 
  
  We'd love your feedback and ideas — drop a note to info at documentcloud dot org or join
  us in the News Nerdery Slack in the #proj-documentcloud channel.
instructions: ''
type: object
documents:
  - selected
  - query
properties:
  prompt:
    title: Give a GPT-3 style prompt
    type: string
  value:
    title: Put a tag here if you would like to save the results as a key value pair on the document.
    type: string

required:
  - prompt
categories:
  - ai
  - premium
cost:
  price: 1
  amount: 1
  unit: page
