title: GPT-3 Playground
description: >-
  Describe your investigation and this will use GPT-3 to try and assess if a given document is relevant or irrelevant. Can get expensive.
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties can just be blank if you do not need any input data
properties:
  # the key is the name of the variable that will be returned to your code
  investigation:
    # the title is what will be shown as the form label
    title: Investigation
    # a string is text
    type: string
  prompt1:
    # the title is what will be shown as the form label
    title: Add an additional category for it to try to fill in, such as Sentiment 
    # a string is text
    type: string
  prompt2:
    # the title is what will be shown as the form label
    title: Add an additional category for it to try to fill in, such as Sentiment 
    # a string is text
    type: string

