title: GPT-3 Playground
description: >-
  Describe your investigation and this will use GPT-3 to try and assess if a given document is relevant or irrelevant. Please limit to a few dozen selections at a time.
type: object
# How does this add-on accept documents
# If more than one type is specified, the user will be prompted to choose one
documents:
  # By the current search query
  - query
  # By the currently selected documents
  - selected
# Properties can just be blank if you do not need any input data
properties:
  # the key is the name of the variable that will be returned to your code
  investigation:
    # the title is what will be shown as the form label
    title: Investigation
    # a string is text
    type: string

