
name: Update Config
on:
  push:
    branches:
      - main
    paths:
      - config.yaml

jobs:
  Update-Config:
    uses: MuckRock/documentcloud-addon-workflows/.github/workflows/update-config.yml@v1

env:
  API_KEY: ${{ secrets.API_KEY }}
